### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Zarfab** [huochaitiantang/pytorch-deep-image-matting#25]
Hello!
I would like to thank you for developping this and sharing your code. As part of my job at University of Mons (UMONS - Belgium), I will need to use your pretrained model and modify some of your scripts. The later goal is to create a deep learning live demo for general public and hopfully raise awareness for new technologies - No comercial use.
Do you plan to [add a licence](https://choosealicense.com/) to this project? If not, do you let me use and modify your code  - with citation of your work?
Regards.

PS:As this is quite urgent, could you answser before october 18th please?

**Comment by huochaitiantang** [comment]
Hi,
We do not have the plan to add a license and you can use and modify the code for non-commercial purposes. The training dataset comes from Adobe, so the pre-trained models included in this repository could only be used and distributed for non-commercial purposes too.

**Comment by Zarfab** [comment]
Perfect! Thanks for your reply.
