### ISSUE TITLE
How to calculate connectivity error

### ISSUE THREAD

**Issue by Charlie0215** [huochaitiantang/pytorch-deep-image-matting#26]
Hello, I am a noob for image matting task and I was wondering how did you calculate the connectivity error. Could you share some codes on this?

**Comment by huochaitiantang** [comment]
This project did not implement the calculation of Grad Error and Connectivity Error. We adopted the available evaluation code from Deep-Image-Matting official page(https://sites.google.com/view/deepimagematting).

**Comment by Charlie0215** [comment]
Thanks so much!
