### ISSUE TITLE
The new pretrained model released on 9th Sep caused corrupt when load

### ISSUE THREAD

**Issue by punkcure** [huochaitiantang/pytorch-deep-image-matting#39]
The projects is corrupted when load the new pretrained model released on 9th Sep
![image](https://user-images.githubusercontent.com/7077441/93335247-b8d50480-f858-11ea-8bb6-457f38bb0766.png)

**Comment by exition** [comment]
me too , wrong encoded pth file

**Comment by xiaoqiangsheng2016** [comment]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 5: invalid continuation byte

me too

**Comment by huochaitiantang** [comment]
Hey guys, the bug is fixed now, and the patch is upstreamed!
Please see: https://github.com/huochaitiantang/pytorch-deep-image-matting/blob/f5f909dba65c6538b38b23190af5eb5665b518be/core/demo.py#L10-L31
