### ISSUE TITLE
Doubts about the alpha_loss

### ISSUE THREAD

**Issue by babyformula** [huochaitiantang/pytorch-deep-image-matting#6]
After read the code and implemented the training, I had some doubts about the alpha_loss calculation. According to the paper, the formulation'd relate to GT alpha and the Pred alpha, why was the trimap involved? And during the training, the alpha_loss was always staying at about 0.2, never got converged.
Glad to talk with you.

**Comment by huochaitiantang** [comment]
1, the pred_alpha is the output of network and whose value is 0~1.
2, +1. can avoid dividing by 0.
